### ISSUE TITLE
alternative drive url

### ISSUE THREAD

**Issue by JEONG8652** [bcmi/ProPIH-Painterly-Image-Harmonization#2]
Hello, Thank you for your impressive work.

I would like to try testing your method, but I can't create and account for Baidu cloud so I can't download the weight.
would you mind uploading the weight file on alternative drive (ex. Google Drive)?

Thank you.

**Comment by ustcnewly** [comment]
We have uploaded the model to OneDrive.

**Comment by ustcnewly** [comment]
Thanks for your interest in our work. We have uploaded the model to OneDrive.

 

Best regards,

Li Niu

 

发件人: Jaehee_Jeong ***@***.***> 
发送时间: 2024年5月30日 0:14
收件人: bcmi/ProPIH-Painterly-Image-Harmonization ***@***.***>
抄送: Subscribed ***@***.***>
主题: [bcmi/ProPIH-Painterly-Image-Harmonization] alternative drive url (Issue #2)

 

Hello, Thank you for your impressive work.

I would like to try testing your method, but I can't create and account for Baidu cloud so I can't download the weight.
would you mind uploading the weight file on alternative drive (ex. Google Drive)?

Thank you.
